### ISSUE TITLE
Please pay attention!! (off topic)

### ISSUE THREAD

**Issue by Q2114** [MCMrARM/mc-w10-versiondb#14]
Restore site mrarm.io/skinstudio/# please, I can't play without my 3d skins!And to the site code, two files are missing!
![IMG_20230217_185321](https://user-images.githubusercontent.com/102694456/219715149-68e61f08-89e4-43c1-9cc5-8b334cad7102.jpg)
![IMG_20230217_185151](https://user-images.githubusercontent.com/102694456/219715158-95717869-b850-4cdc-858d-11807e9a84e6.jpg)
and there more "zip"... please fix this :_(

**Comment by MCMrARM** [comment]
site is back, I had a system update fail on the VPS yesterday and ended up quiickly re-setting the entire website on a second VPS as a result

**Comment by Q2114** [comment]
Wow, take lessons on JavaScript)))
Thank you very much, I already thought I would be left without my skins: _)))))
