### ISSUE TITLE
License

### ISSUE THREAD

**Issue by CheatCod** [MCMrARM/mc-w10-versiondb#15]
Hello! I'm wondering if we can possibly use this repo for our [project](https://github.com/Lodestone-Team/lodestone) (a Minecraft server wrapper), which is open source and licensed with APGL.

**Comment by MCMrARM** [comment]
This repository does not contain any copyrightable information in my jurisdiction, therefore there is nothing stopping you from doing what you have suggested.

Please consider data in this repository public domain, or on the terms of Unlicense license.

Please note that this statement does not refer to any other repositories such as the launcher one.
