### ISSUE TITLE
Can you make a verison of toolbox for minecraft that doesnt require updating

### ISSUE THREAD

**Issue by Fabian1219** [MCMrARM/mc-w10-versiondb#3]
I love the new update you implement the mouse sensor and I want to play on severs but cant because am not up to date I was wondering if you could make it were I can just launch toolbox anyday without "Your version of minecraft is unsupported thank you

**Comment by Fabian1219** [comment]
You did something that many people wanted for a long time :)

**Comment by MCMrARM** [comment]
no and wrong repo
