### ISSUE TITLE
Add 0.12.0

### ISSUE THREAD

**Issue by Godeps2891** [MCMrARM/mc-w10-versiondb#6]
![image](https://user-images.githubusercontent.com/54289108/123198978-5297a500-d4ae-11eb-89fa-065b6fda6c4f.png)

uploaded some time ago to the omniarchive discord 

https://mega.nz/file/pvh00CjR#S3m8LsrkblthCtF_tl-dDhcGacUjeRsGVrMFNfhMuuc

**Comment by MCMrARM** [comment]
The versiondb is only for UUIDs, which can not be extracted from anything other than the WU DataStore archive.
